apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task1-app
  name: task1-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task1-app
  template:
    metadata:
      labels:
        app: task1-app
    spec:
      containers:
      - name: task1
        image: ssan91/task1:v1
        ports:
        - containerPort: 80
